# 服务端口
server:
  port: 10000

# dataSource
spring:
  application:
    name: cloud-gateway-zuul

eureka: 
  instance:
    hostname: 127.0.0.1
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}
  client: 
    serverUrl: 
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/
    healthcheck:
      enabled: true
    
endpoints:
  enabled: false
  info: 
    enabled: true
  health:
    enabled: true
    
# hystix的超时时间
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 30000
    
zuul:
  host:
    maxTotalConnections: 256
    maxPerRouteConnections: 256
  routes:
    module-sys:
      path: /rest/sys/**
      stripPrefix: false
      serviceId: module-sys
    module-base:
      path: /rest/base/**
      stripPrefix: false
      serviceId: module-base
      
    
    